{
  pkgs,
  ...
}:
{
  programs.caelestia = {
    enable = true;
    systemd = {
      enable = true;
      target = "graphical-session.target";
      environment = [
        "QT_QPA_PLATFORM=wayland"
        "QT_QPA_PLATFORMTHEME=qt6ct"
        "QUICKSHELL_ENABLE_PORTAL=1"
      ];
    };
    settings = { };
    cli = {
      enable = true; # Also add caelestia-cli to path
      settings = { };
    };
  };

  # The caelestia.service unit generated by the programs.caelestia module
  # above does NOT set LimitNOFILE, so the process falls back to the Linux
  # kernel's default soft limit of 1024 (confirmed via /proc/<pid>/limits)
  # even though `systemctl --user show caelestia.service -p LimitNOFILE`
  # reports systemd's much higher manager-level default (524288) - that
  # manager default is NOT automatically inherited by a unit that doesn't
  # request it. Under real usage (many QProcess spawns for nmcli, tray
  # icons, media players, etc.) this 1024 cap gets exhausted, causing
  # "QProcess: Cannot create pipe (Too many open files)" and starving
  # sibling processes (VSCode/NeoHtop failed to launch; Electron/libuv
  # apps are especially fd-hungry) sharing the same session/cgroup fd
  # pressure. Merging an explicit LimitNOFILE here (HM merges Service
  # attrsets for the same unit name across module declarations) fixes it
  # without touching the upstream caelestia-shell module.
  systemd.user.services.caelestia.Service.LimitNOFILE = "524288";

  # Additional packages to support caelestia shell
  home.packages = with pkgs; [
    # Icons
    papirus-icon-theme
    material-symbols

    # Packages
    dart-sass # Sass compiler
    ydotool # Wayland input automation tool
    fuzzel # Fuzzy launcher
    slurp # Select a region on the screen
    fish # Fish shell
    cava # Audio visualizer
    aubio # Audio analysis library
    glibc # GNU C Library
    kdePackages.qt6ct # Qt6 configuration tool
    qt6.qtdeclarative # Qt6 declarative module
    libqalculate # Calculator library
    swappy # Image editor for screenshots
    ibm-plex # IBM Plex font
    imagemagick # Image manipulation tool
    safeeyes # Eye protection tool
    gpu-screen-recorder # Screen recorder that uses GPU for encoding

    # Might be the wrong packages
    gdbuspp
    libpulseaudio
    rubyPackages_3_4.glib2
    gcc
  ];
}
